version: 2.1

# jobs:
#   build-code:
#    steps:
#      when:
#       condition:
#           - << pipeline.parameters.build-code >>
#       steps:
#         - checkout
#         - run:
#             name: "Say hello"
#             command: "echo Hello, World!"

#   validate-helm:
#     steps:
#       condition:
#         and:
#           - << pipeline.parameters.helm-validate >>
#       docker:
#       - image: cimg/base:stable
#       steps:
#         - checkout
#         - run:
#             name: "Say hello helm"
#             command: "echo Hello, helm!"

my-job:
  steps:
    when:
      condition:
        or:
          - << pipeline.parameters.helm-validate >>
      steps:
        - run: ./deploy
